version: '3'
services:
    sonarqube:
        ports:
            - '9000:9000'
        volumes:
            - sonarqube:/opt/sonarqube/
        image: sonarqube
        networks:
            - jenkins

    jenkins:
        build: ./jenkins/master
        image: jenkins-jb/master:1.0
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - jenkins_home:/var/jenkins_home
        ports:
            - '80:8080'
            - '5005:50000'
        networks:
            - jenkins

    jenkins-slave:
        build: ./jenkins/slave
        restart: always
        environment:
            - 'JENKINS_URL=http://jenkins:8080'
        image: jenkins-jb/slave:1.0
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock # Expose the docker daemon in the container
            - ./volume:/home/jenkins # Avoid mysql volume mount issue
        depends_on:
            - jenkins
        networks:
            - jenkins

volumes:
    jenkins_slave:
    jenkins_home:
    sonarqube:


networks:
    jenkins:
