pipeline{
    agent any

    environment {
    IMAGE_NAME='jb_course_test_ratings_app'
    VERSION="v${env.BUILD_NUMBER}"
    REPO='fro1m'
    CREDENTIALS_ID='docker-cred'
    }

    stages {
        stage('Build'){
            steps {
                script {
                    //Build the Docker image for the build stage
                    sh 'docker build --target build --tag ${IMAGE_NAME}:${VERSION}-build -f welcome/app/bookinfo/src/ratings/Dockerfile .'
                }
            }

        }

        stage('Lint') {
            steps {
                script{
                    sh 'docker build --target lint-test --tag ${IMAGE_NAME}:${VERSION}-lint-test -f welcome/app/bookinfo/src/ratings/Dockerfile .'
                }
            }
        }


        stage('Push') {
            steps{
                script{
                    //Push the docker image to repo
                    docker.withRegistry('https://index.docker.io/v1/', "${CREDENTIALS_ID}") {
                        sh 'docker build --target run --tag ${REPO}/${IMAGE_NAME}:${VERSION} -f welcome/app/bookinfo/src/ratings/Dockerfile .'
                        sh 'docker push ${REPO}/${IMAGE_NAME}:${VERSION}'
                    }
                }
            }
        }
    }
}
