apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Chart.Name }}-sql
  namespace: default
spec:
  selector:
    matchLabels:
      app: {{ .Values.mysql.label }}
  replicas: 1
  template:
    metadata:
      labels:
        app:  {{ .Values.mysql.label }}
    spec:
      containers:
      - name:  {{ .Values.mysql.label }}
        image:  {{ .Values.mysql.image }}
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.mysql.envVar1 }}  
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: {{ .Values.mysql.envVar2 | quote }}
        - name: MYSQL_USER
          value: {{ .Values.mysql.envVar3 }}
        - name: MYSQL_PASSWORD
          value: {{ .Values.mysql.envVar4 }}
        - name: MYSQL_DATABASE
          value: {{ .Values.mysql.envVar5 }}
